include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AlbumPref
AlbumPref_FILES = /mnt/d/codes/albumpref/albumprefhook/Tweak.xm
AlbumPref_FRAMEWORKS = Foundation UIKit CoreGraphics

ARCHS = armv7 armv7s arm64 arm64e
AlbumPref_ARCHS = armv7 armv7s arm64 arm64e

include $(THEOS_MAKE_PATH)/tweak.mk
